### PR TITLE
Markdown previews of posts

### LINKED ISSUE #99: Preview post
Ability to preview before posting.

### PR DESCRIPTION
**Pull request by drewwells**
Preview hide/shows based on value of textarea
The composition textarea resizes based off input

004f26e59cff1ef6ac4654c3c90bfaaa

This resolves #99

### CODE REVIEW

**Comment by marktheunissen** [comment]
Great! Code looks good, need to test this afternoon.

**Comment by pifantastic** [comment]
Yeah, this is great.

Would it be better to move the preview below the "Post" button? That way if the preview gets really large, the button isn't lost? Just a comment, not sure if it's really worth it.

**Comment by drewwells** [comment]
I copied the visuals of StackOverflow, so I didn't give this much thought.  Maybe test out a big post on SO and see if it's to your liking?

**Comment by pifantastic** [comment]
Ohh, I didn't realize that. Ignore me, I think it's better to follow precedent. Modeling after SO is a good choice.

**Comment by Fil** [comment]
Personally, I don't like this idea of a preview; I prefer an "edit" button
for when I'm unhappy with the result.

**Comment by drewwells** [comment]
The ability to write markdown and see what HTML output you get is something
I think we can't do without.  Edit would be handy, but preview provides
immediate feedback for getting the HTML output correct.

**Comment by Fil** [comment]
I don't think it is useful _for me_. I even think it's a negative: it carries some complexity and mental load when you compose your text and you see it appear twice. YMMV, of course. (This problem doesn't exist with an optional tab, just like the github comments I'm using right now.)

**Comment by pifantastic** [comment]
Yeah, it may be better to opt for a preview button. For now, I vote we
merge this in, and work on the UX later.

**Comment by marktheunissen** [comment]
I agree that it should be optional and a toggle button would be perfect for that. If you want to merge and then fix up UX later that's fine with me.

**Comment by marktheunissen** [comment]
This works great! Need to add a toggle button sometime, but merging now.

**Comment by drewwells** [comment]
File a ticket for the toggling

**Pull request merged**
