### PR TITLE
Pagination

### LINKED ISSUE #35: Pagination support.
A GET request to /api/posts should return the first X posts, then perhaps infinite scroll to load more?

### PR DESCRIPTION
**Pull request by pifantastic**
Closes #35

### CODE REVIEW

**Comment by Fil** [comment]
Is it useful to say I've tested it and it works?

**Comment by marktheunissen** [comment]
@Fil Yes, thanks for that.

@pifantastic This works great and is an effective stop-gap. Nice work. I had some thoughts about the limitations of this approach and I'll put them here in case others are interested.

If more than `PageSize` posts are made between consecutive polling requests (3 seconds by default), they won't be fetched. We could change the poll to use 'after' and pass a highwater mark, but there is no good method of doing this given our environment. For example, imagine this simplified representation:

G - 190
F - 189
E - 188
D - 187
C - 186
B - 185
A - 184

We have posts with IDs of `A..G`, and timestamps `184..190`. The list is sorted by timestamp. If we ask for all posts after ID `G`, but 10 new posts arrive with timestamp `189`, we'll never get them on the frontend. If we use timestamp, we have the same problem, asking for all posts after `190` will fail to retrieve anything that arrives in the past. Doing a hard refresh of the page will collect all missing data, of course.

However, I think that this is fine for now. We can set the `PageSize` to 50. If someone is getting more than 50 posts every 3 seconds, they're being spammed. 

With inotify support, this problem goes away. I've opened a new issue for that:

https://github.com/vole/vole/issues/84

**Comment by Fil** [comment]
Pagination is broken on the personal profile. Possibly because filtering on user is done after pagination.

**Comment by pifantastic** [comment]
D'oh. I never thought to check there @Fil. Good point. Does it just return everyone's posts?

Should be an easy fix.

**Comment by marktheunissen** [comment]
@Fil, I did test it and it worked for me. What are the exact steps to reproduce?

**Comment by marktheunissen** [comment]
Ah ok, so if you go to your profile but the frontend hasn't loaded any of your own posts, you won't see anything.

Every time you hit 'load more', it's loading the next 50 posts, which may or may not include your own posts - so if you have 4 posts in the next 50, then those 4 appear. 

Correct behavior is to query for 50 of only your own posts.

**Comment by Fil** [comment]
I tried again with a fresh clone from https://github.com/vole/vole.git

"My profile" lists 4 posts; "load more" loads another 6; then another 11;
then 0…

**Comment by Fil** [comment]
exactly

**Comment by pifantastic** [comment]
Thanks @Fil for finding stuff like this so quickly :thumbsup:

**Comment by Fil** [comment]
There are only two buttons to try :)

**Comment by pifantastic** [comment]
We will send you a complimentary live vole when we hit version 1.0

**Comment by marktheunissen** [comment]
I'm working on this now.

**Pull request merged**
