### PR TITLE
Markdown

### PR DESCRIPTION
**Pull request by pifantastic**

### CODE REVIEW

**Comment by Fil** [comment]
works perfectly

**Comment by marktheunissen** [comment]
Here's an edge case, try post the following URL:

`http://www.slate.com/content/dam/slate/blogs/bad_astronomy/2012/12/best_of_2012_photos/SDO_arch.jpg.CROP.article920-large.jpg`

screen shot 2013-06-30 at 11 31 51 am

However, if I post the markdown image tag, it works great:

``` markdown
![Space](http://www.slate.com/content/dam/slate/blogs/bad_astronomy/2012/12/best_of_2012_photos/SDO_arch.jpg.CROP.article920-large.jpg)
```

screen shot 2013-06-30 at 11 33 02 am

I think we should remove the linkify stuff and only support markdown format. Is that too restrictive?

**Comment by pifantastic** [comment]
Yeah, I considered that. I'm just afraid that markdown is too complicated
for the casual user. I can never remember the syntax for links :P

**Comment by marktheunissen** [comment]
Yeah. The other issue right now is that two consecutive lines are combined into one:

```
test line
test line two
```

becomes:

```
test line test line two
```

I think we need to get an implementation of Github Flavored Markdown specifically, which handles linkifying and solves the above issue.

https://help.github.com/articles/github-flavored-markdown

**Comment by marktheunissen** [comment]
Another issue is that I can currently use `<script>` tags in a post and they aren't escaped. Security wise this is fine for people with newer browsers as Content Security Policy headers will prevent the script from executing, but we need to escape these.

**Comment by Fil** [comment]
Also, I noticed that a line starting with a #hashtag makes a title. Usually
it should be "hash-space title", I think. So showdown is probably not
perfect. And yes, the link shortcut for markdown is indeed ridiculously
difficult to remember.

**Comment by marktheunissen** [comment]
@Fil Good catch, that should be fixed!

**Pull request merged**
