### PR TITLE
Listen to localhost only by default, but make it configurable.

### PR DESCRIPTION
**Pull request by pifantastic**
Address https://github.com/vole/vole/issues/71

### CODE REVIEW

**Comment by marktheunissen** [comment]
Looks good.

**Comment by marktheunissen** [comment]
Although should it be "listen" instead of "host" ? That's the IP address that it listens on, right? I couldn't find explicit info in the WebGo docs.

**Comment by pifantastic** [comment]
You mean in the config? I did struggle with the name. I'm okay changing it to `listen` if you'd like me to.

**Comment by marktheunissen** [comment]
Yeah I think it should be as consistent with popular open source web servers as possible.

For example, Apache and Nginx servers: 

http://httpd.apache.org/docs/current/mod/mpm_common.html#Listen
http://wiki.nginx.org/HttpCoreModule#listen

So +1 for the change.

**Comment by pifantastic** [comment]
@marktheunissen done.

**Pull request merged**
